import StyledComponentsRegistry from "@/lib/AntRegistry";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Provider from "./Provider";
import { ExamsProvider } from "./context/ExamsContext";
import { ExamQuestionsProvider } from "./context/ExamQuestionsContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CodexGuru",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <StyledComponentsRegistry>
            <ExamsProvider>
              <ExamQuestionsProvider>
    
                  <main>
                    <Header />
                    {children}
                  </main>
              </ExamQuestionsProvider>
            </ExamsProvider>
          </StyledComponentsRegistry>
        </Provider>
      </body>
    </html>
  );
}
